### ISSUE TITLE
Help me to fix the mergify.yml

### ISSUE THREAD

**Issue by mengalong** [Mergifyio/demo#11]
Hello
I try to use mergify in my test project find that cannot merge pull request automic.
Could you help me fix the problem,is there any error with my config file.

here is the pull request: https://github.com/mengalong/SA/pull/3

Thank you very much!

**Comment by jd** [comment]
Hi @mengalong,
I've reached you by email.

**Comment by mengalong** [comment]
Tanks, but I havenot review your email. please check it
